version: '3.2'

services:
  mysql:
    #container_name: mysql
    #image: mariadb:10.6.4-focal
    image: mysql:8
    restart: always
    ports: 
      - "3308:3306"
    environment:
      MYSQL_DATABASE: prestashop
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: prestashop
    volumes:
      - ./mysql/init-prestashop.sql:/docker-entrypoint-initdb.d/init-prestashop.sql
      - persistent:/var/lib/mysql
    networks:
      - prestashop_network
  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:8.2.3
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8082:80
    environment:
      DB_SERVER: mysql
      DB_NAME: prestashop
      DB_USER: prestashop
      DB_PASSWD: test
      PS_FOLDER_ADMIN: admin4577
      PS_FOLDER_INSTALL: install4577
      PS_INSTALL_AUTO: 1        # ⚡ Instalación automática
      PS_DEV_MODE: 1            # ⚡ Habilita modo desarrollador
      PS_LANGUAGE: es           # Idioma por defecto
      PS_COUNTRY: CO            # País por defecto
      PS_TIMEZONE: America/Bogota
      PS_CURRENCY: COP              # Moneda predeterminada (Peso Colombiano)
      ADMIN_MAIL: admin@epayco.com  # 🔑 Usuario admin del Back Office
      ADMIN_PASSWD: admin123        # 🔑 Contraseña admin
    networks:
      - prestashop_network
    volumes:
      - ./modules/testModule:/var/www/html/modules
      - ./themes/myTheme:/var/www/html/themes/myTheme
      - psdata:/var/www/html
      - ./conf/app.ini:/usr/local/etc/php/conf.d/app.ini

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:mysql
    ports:
      - 8089:80
    restart: always
    environment:
        PMA_ARBITRARY: 1
        PMA_HOST: mysql
        MYSQL_USER: root
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: test
    depends_on:
      - mysql
    networks:
      - prestashop_network

networks:
  prestashop_network:

volumes:
  psdata:
  persistent:
